### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by fromEternal** [Mateusz-Grzelinski/handheldcamera#2]
Which android sensor app would you prefer? Can you make YouTube tutorial regarding this handheld camera? And any plans to update your script to work in 2.8 ?

**Comment by Mateusz-Grzelinski** [comment]
I haven't looked for a long in this project. In the end rotation capturing sort of worked, but capturing of movement was failure. We did't really investigated it. I suppose I messed up calculating location from acceleration. But event if I made it right, it is still difficult to capture movement from acceleration, because if there is even slight mismatch in calculation, object is never going to stop. I learned it the hard way.
I will not have time to work on this surely until February.

**Comment by Mateusz-Grzelinski** [comment]
i will clean up and update repo for you, forgot to do it at the projet end
